
//小作业 老友记输出
#include<stdio.h>
#include<windows.h>
void Spoke(char name[1000],int time);
int main()
{
Spoke("There's nothing to tell! He's just some guy I work with!\n",1000);
Spoke("Come on, you're going out with the guy! There's gotta be something wrong with him!\n",3000);
Spoke(" All right Joey, be nice.  So does he have a hump? A hump and a hairpiece?\n",4000);
Spoke(" Wait, does he eat chalk?\n",4000);
Spoke("Just, 'cause, I don't want her to go through what I went through with Carl- oh!\n",3000);
Spoke("Okay, everybody relax. This is not even a date. It's just two people going out to dinner and- not having sex.\n",4000);
Spoke("Sounds like a date to me.\n",5000);
Spoke("Chandler: Alright, so I'm back in high school, I'm standing in the middle of the cafeteria, and I realize I am totally naked.\n",4000);
Spoke("All: Oh, yeah. Had that dream.\n",6000);
Spoke("Chandler: Then I look down, and I realize there's a phone... there.\n",3000);
Spoke("Joey: Instead of...?\n",5000);
Spoke("Chandler: That's right.\n",3000);
Spoke("Joey: Never had that dream.\n",3000);
Spoke("Phoebe: No.\n",3000);
Spoke("Chandler: All of a sudden, the phone starts to ring. Now I don't know what to do, everybody starts looking at me. \n",3000);
Spoke("Monica: And they weren't looking at you before?!\n",6000);
Spoke("Chandler: Finally, I figure I'd better answer it, and it turns out it's my mother, which is very-very weird, because- she never calls me!\n",4000);
Spoke("Ross: (mortified) Hi.\n",6000);
Spoke("Joey: This guy says hello, I wanna kill myself.\n",3000);
Spoke("Ross: I just feel like someone reached down my throat, grabbed my small intestine, pulled it out of my mouth and tied it around my neck...\n",4000);
Spoke("Chandler: Cookie?\n",6000);
Spoke("Monica: (explaining to the others) Carol moved her stuff out today.\n",4000);
Spoke("Joey: Ohh\n",4000);
Spoke("Monica: (to Ross) Let me get you some coffee.\n",4000);
Spoke("Ross: Thanks.\n",3000);
Spoke("Phoebe: Ooh! Oh! (She starts to pluck at the air just in front of Ross.)\n",3000);
Spoke("Ross: No, no don't! Stop cleansing my aura! No, just leave my aura alone, okay?\n",4000);
Spoke("Phoebe: Fine!  Be murky!\n",4000);
Spoke("Ross: I'll be fine, alright? Really, everyone. I hope she'll be very happy.\n",4000);
Spoke("Monica: No you don't.\n",5000);
Spoke("Ross: No I don't, to hell with her, she left me!\n",4000);
Spoke("Joey: And you never knew she was a lesbian...\n",4000);
Spoke("Ross: No!! Okay?! Why does everyone keep fixating on that? She didn't know,  how should I know?\n",4000);
Spoke("Chandler: Sometimes I wish I was a lesbian... (They all stare at him.) Did I say that out loud?\n",5000);
Spoke("Ross: I told mom and dad last night, they seemed to take it pretty well.\n",5000);
Spoke("Ross: Sorry.\n"",4000);",5000);
Spoke("Joey: Alright Ross, look. You're feeling a lot of pain right now. You're angry. You're hurting. Can I tell you what the answer is?\n",4000);
Spoke("Joey: Strip joint! C'mon, you're single! Have some hormones!\n",6000);
Spoke("Ross: I don't want to be single, okay? I just... I just- I just wanna be married again!\n",6000);
Spoke("Chandler: And I just want a million dollars! (He extends his hand hopefully.)\n",6000);
Spoke("Monica: Rachel?!\n",6000);
Spoke("Rachel: Oh God Monica hi! Thank God! I just went to your building and you weren't there and then this guy with a big hammer said you might be here and you are, you are!\n",4000);
Spoke("Waitress: Can I get you some coffee?\n",8000);
Spoke("Monica: (pointing at Rachel) De-caff. (to All) Okay, everybody, this is Rachel, another Lincoln High survivor. (to Rachel) This is everybody, this is Chandler, and Phoebe, and Joey, and- you remember my brother Ross? \n",4000);
Spoke("Rachel: Hi, sure!\n",8000);
Spoke("Ross: Hi. \n",4000);
Spoke("Monica: So you wanna tell us now, or are we waiting for four wet bridesmaids?\n",4000);
Spoke("Rachel: Oh God... well, it started about a half hour before the wedding. I was in the room where we were keeping all the presents, and I was looking at this gravy boat. This really gorgeous Lamauge gravy boat. When all of a sudden- (to the waitress that brought her coffee) Sweet 'n' Lo?- I realized that I was more turned on by this gravy boat than by Barry! And then I got really freaked out, and that's when it hit me: how much Barry looks like Mr. Potato Head. Y'know, I mean, I always knew looked familiar, but... Anyway, I just had to get out of there, and I started wondering 'Why am I doing this, and who am I doing this for?'. (to Monica) So anyway I just didn't know where to go, and I know that you and I have kinda drifted apart, but you're the only person I knew who lived here in the city.\n",5000);
Spoke("Monica: Who wasn't invited to the wedding.\n",8000);
Spoke("Rachel: Ooh, I was kinda hoping that wouldn't be an issue...\n",6000); 
Spoke("Monica: Now I'm guessing that he bought her the big pipe organ, and she's really not happy about it. \n",6000);
Spoke("Chandler: (imitating the characters) Tuna or egg salad?  Decide!\n",6000);
Spoke("Ross: (in a deep voice) I'll have whatever Christine is having.\n",6000);
Spoke("Rachel: (on phone) Daddy, I just... I can't marry him! I'm sorry. I just don't love him. Well, it matters to me! \n",6000);
Spoke("Phoebe:  If I let go of my hair, my head will fall off. \n",6000);
Spoke("Chandler: (re TV) Ooh, she should not be wearing those pants. \n",6000);
Spoke("Joey: I say push her down the stairs. \n",5000);
Spoke("Phoebe, Ross, Chandler, and Joey:  Push her down the stairs! Push her down the stairs! Push her down the stairs!\n",5000);
Spoke("Rachel: C'mon Daddy, listen to me! It's like, it's like, all of my life, everyone has always told me, 'You're a shoe! You're a shoe, you're a shoe, you're a shoe!'. And today I just stopped and I said, 'What if I don't wanna be a shoe? What if I wanna be a- a purse, y'know? Or a- or a hat! No, I'm not saying I want you to buy me a hat, I'm saying I am a ha- It's a metaphor, Daddy!\n",6000);
Spoke("Ross: You can see where he'd have trouble.\n",8000);
Spoke("Rachel: Look Daddy, it's my life. Well maybe I'll just stay here with Monica. \n",6000);
Spoke("Monica: Well, I guess we've established who's staying here with Monica...\n",7000);
Spoke("Rachel: Well, maybe that's my decision. Well, maybe I don't need your money. Wait!! Wait, I said maybe!!\n",6000);
Spoke("Monica: Just breathe, breathe.. that's it. Just try to think of nice calm things... Phoebe: (sings) Rain drops on roses and rabbits and kittens, (Rachel and Monica turn to look at her.) bluebells and sleighbells and- something with mittens... La la la la...something and noodles with string.  These are a few...\n",4000);
Spoke("Rachel: I'm all better now.\n",8000);
Spoke("Phoebe: (grins and walks to the kitchen and says to Chandler and Joey.) I helped!\n",4000);
Spoke("Monica: Okay, look, this is probably for the best, y'know? Independence. Taking control of your life.  The whole, 'hat' thing.\n",4000);
Spoke("Joey: (comforting her) And hey, you need anything, you can always come to Joey. Me and Chandler live across the hall. And he's away a lot.\n",4000);
Spoke("Monica: Joey, stop hitting on her! It's her wedding day!\n",4000);
Spoke("Joey: What, like there's a rule or something?\n",4000);
Spoke("Chandler: Please don't do that again, it's a horrible sound.\n",4000);
Spoke("Paul: (over the intercom) It's, uh, it's Paul.\n",4000);
Spoke("Monica: Oh God, is it 6:30?  Buzz him in!\n",4000);
Spoke("Joey: Who's Paul?\n",4000);
Spoke("Ross: Paul the Wine Guy, Paul?\n",4000);
Spoke("Monica: Maybe. \n",4000);
Spoke("Joey: Wait. Your 'not a real date' tonight is with Paul the Wine Guy?\n",4000);
Spoke("Ross: He finally asked you out?\n",4000);
Spoke("Monica: Yes!\n",4000);
Spoke("Chandler: Ooh, this is a Dear Diary moment.\n",4000);
Spoke("Monica: Rach, wait, I can cancel...\n",4000);
Spoke("Rachel: Please, no, go, that'd be fine!\n",5000);
Spoke("Monica: (to Ross) Are, are you okay? I mean, do you want me to stay?",5000);
Spoke("Ross: (choked voice) That'd be good...",5000);
Spoke("Monica: (horrified) Really?\n",5000);
Spoke("Ross: (normal voice) No, go on! It's Paul the Wine Guy!\n",5000);
Spoke("Phoebe: What does that mean? Does he sell it, drink it, or just complain a lot? (Chandler doesn't know.)\n",5000);
Spoke("Monica: Hi, come in! Paul, this is.. (They are all lined up next to the door.)... everybody, everybody, this is Paul.\n",5000);
Spoke("All: Hey! Paul! Hi! The Wine Guy! Hey!\n",5000);
Spoke("Chandler: I'm sorry, I didn't catch your name. Paul, was it?\n",5000);
Spoke("Monica: Okay, umm-umm, I'll just--I'll be right back, I just gotta go ah, go ah...\n",5000);
Spoke("Ross: A wandering?\n",5000);
Spoke("Monica: Change!  Okay, sit down. (Shows Paul in) Two seconds.\n",5000);
Spoke("Phoebe: Ooh, I just pulled out four eyelashes. That can't be good.\n",5000);
Spoke("Joey:  Hey, Paul!\n",5000);
Spoke("Paul: Yeah?\n",5000);
Spoke("Joey: Here's a little tip, she really likes it when you rub her neck in the same spot over and over and over again until it starts to get a little red.\n",5000);
Spoke("Monica: (yelling from the bedroom) Shut up, Joey!\n",5000);
Spoke("Ross: So Rachel, what're you, uh... what're you up to tonight?\n",5000);
Spoke("Rachel: Well, I was kinda supposed to be headed for Aruba on my honeymoon, so nothing!\n",5000);
Spoke("Ross: Right, you're not even getting your honeymoon, God.. No, no, although, Aruba, this time of year... talk about your- (thinks) -big lizards... Anyway, if you don't feel like being alone tonight, Joey and Chandler are coming over to help me put together my new furniture.\n",5000);
Spoke("Chandler: (deadpan) Yes, and we're very excited about it. \n",5000);
Spoke("Rachel: Well actually thanks, but I think I'm just gonna hang out here tonight.  It's been kinda a long day.\n",5000);
Spoke("Ross: Okay, sure.\n",5000);
Spoke("Joey: Hey Pheebs, you wanna help?\n",5000);
Spoke("Phoebe: Oh, I wish I could, but I don't want to.\n",5000);
Spoke("Phoebe: (singing) Love is sweet as summer showers, love is a wondrous work of art, but your love oh your love, your love...is like a giant pigeon...crapping on my heart.  La-la-la-la-la- (some guy gives her some change and to that guy) Thank you. (sings) La-la-la-la...ohhh!\n",5000);
Spoke("Ross: (squatting and reading the instructions) I'm supposd to attach a brackety thing to the side things, using a bunch of these little worm guys. I have no brackety thing, I see no whim guys whatsoever and- I cannot feel my legs.\n",5000);
Spoke("(Joey and Chandler are finishing assembling the bookcase.)\n",5000);
Spoke("Joey: I'm thinking we've got a bookcase here.\n",5000);
Spoke("Chandler: It's a beautiful thing.\n",5000);
Spoke("Joey: (picking up a leftover part) What's this?\n",5000);
Spoke("Chandler: I would have to say that is an 'L'-shaped bracket.\n",5000);
Spoke("Joey: Which goes where?\n",5000);
Spoke("Chandler: I have no idea.\n",5000);
Spoke("Joey: Done with the bookcase!\n",5000);
Spoke("Chandler: All finished!\n",5000);
Spoke("Ross: (clutching a beer can and sniffing) This was Carol's favorite beer. She always drank it out of the can, I should have known.\n",5000);
Spoke("Joey: Hey-hey-hey-hey, if you're gonna start with that stuff we're outta here.\n",5000);
Spoke("Chandler: Yes, please don't spoil all this fun.\n",5000);
Spoke("Joey: Ross, let me ask you a question. She got the furniture, the stereo, the good TV- what did you get?\n",5000);
Spoke("Ross: You guys.\n",5000);
Spoke("Chandler: Oh, God.\n",5000);
Spoke("Joey: You got screwed.\n",5000);
Spoke("Chandler: Oh my God!\n",5000);
Spoke("Monica: Oh my God!\n",5000);
Spoke("Paul: I know, I know, I'm such an idiot. I guess I should have caught on when she started going to the dentist four and five times a week. I mean, how clean can teeth get?\n",5000);
Spoke("Monica: My brother's going through that right now, he's such a mess. How did you get through it?\n",5000);
Spoke("Paul: Well, you might try accidentally breaking something valuable of hers, say her-\n",5000);
Spoke("Monica: -leg?\n",5000);
Spoke("Paul: (laughing) That's one way! Me, I- I went for the watch.\n",5000);
Spoke("Monica: You actually broke her watch?  Wow!  The worst thing I ever did was, I-I shredded by boyfriend's favorite bath towel.\n",5000);
Spoke("Paul: Ooh, steer clear of you.\n",5000);
Spoke("Monica: That's right. [Scene: Monica's Apartment, Rachel is talking on the phone and pacing.]\n",5000);
Spoke("Rachel: Barry, I'm sorry... I am so sorry... I know you probably think that this is all about what I said the other day about you making love with your socks on, but it isn't... it isn't, it's about me, and I ju- (She stops talking and dials the phone.) Hi, machine cut me off again... anyway...look, look, I know that some girl is going to be incredibly lucky to become Mrs. Barry Finkel, but it isn't me, it's not me.  And not that I have any idea who me is right now, but you just have to give me a chance too... (The maching cuts her off again and she redials.)\n",5000);
Spoke("Ross: I'm divorced!  I'm only 26 and I'm divorced!\n",5000);
Spoke("Joey: Shut up!\n",5000);
Spoke("Chandler: You must stop! (Chandler hits what he is working on with a hammer and it collapses.)\n",5000);
Spoke("Ross: That only took me an hour.\n",5000);
Spoke("Chandler: Look, Ross, you gotta understand, between us we haven't had a relationship that has lasted longer than a Mento.   You, however have had the love of a woman for four years.   Four years of closeness and sharing at the end of which she ripped your heart out, and that is why we don't do it!  I don't think that was my point!\n",5000);
Spoke("Ross: You know what the scariest part is? What if there's only one woman for everybody, y'know? I mean what if you get one woman- and that's it? Unfortunately in my case, there was only one woman- for her...\n",5000);
Spoke("Joey: What are you talking about? 'One woman'? That's like saying there's only one flavor of ice cream for you. Lemme tell you something, Ross. There's lots of flavors out there. There's Rocky Road, and Cookie Dough, and Bing! Cherry Vanilla. You could get 'em with Jimmies, or nuts, or whipped cream! This is the best thing that ever happened to you! You got married, you were, like, what, eight? Welcome back to the world! Grab a spoon!\n",5000);
Spoke("Ross: I honestly don't know if I'm hungry or horny.\n",5000);
Spoke("Chandler: Stay out of my freezer! \n",5000);
Spoke("Paul: Ever since she walked out on me, I, uh...\n",5000);
Spoke("Monica: What?..... What, you wanna spell it out with noodles?\n",5000);
Spoke("Paul: No, it's, it's more of a fifth date kinda revelation.\n",5000);
Spoke("Monica: Oh, so there is gonna be a fifth date?\n",5000);
Spoke("Paul: Isn't there?\n",5000);
Spoke("Monica: Yeah... yeah, I think there is. -What were you gonna say?\n",5000);
Spoke("Paul: Well, ever-ev-... ever since she left me, um, I haven't been able to, uh, perform.  ...Sexually. \n",5000);
Spoke("Monica: (spitting out her drink in shock) Oh God, oh God, I am sorry... I am so sorry...\n",5000);
Spoke("Paul: It's okay...\n",5000);
Spoke("Monica: I know being spit on is probably not what you need right now. Um... how long?\n",5000);
Spoke("Paul: Two years.\n",5000);
Spoke("Monica: Wow! I'm-I'm-I'm glad you smashed her watch! \n",5000);
Spoke("Paul: So you still think you, um... might want that fifth date?\n",5000);
Spoke("Monica: (pause)...Yeah. Yeah, I do.\n",5000);
Spoke("Priest on TV: We are gathered here today to join Joanne Louise Cunningham and Charles, Chachi-Chachi-Chachi, Arcola in the bound of holy matrimony.\n",5000);
Spoke("Rachel: Oh...see... but Joanne loved Chachi! That's the difference!\n",5000);
Spoke("Ross: (scornful) Grab a spoon. Do you know how long it's been since I've grabbed a spoon? Do the words 'Billy, don't be a hero' mean anything to you? \n",5000);
Spoke("Joey: Great story!  But, I uh, I gotta go, I got a date with Andrea--Angela--Andrea...  Oh man, (looks to Chandler)\n",5000);
Spoke("Chandler: Angela's the screamer, Andrea has cats.\n",5000);
Spoke("Joey: Right.  Thanks.  It's June.  I'm outta here. (Exits.)\n",5000);
Spoke("Ross: Y'know, here's the thing. Even if I could get it together enough to- to ask a woman out,... who am I gonna ask? (He gazes out of the window.)\n",5000);
Spoke("Rachel: Isn't this amazing? I mean, I have never made coffee before in my entire life.\n",5000);
Spoke("Chandler: That is amazing.\n",5000);
Spoke("Joey: Congratulations. \n",5000);
Spoke("Rachel: Y'know, I figure if I can make coffee, there isn't anything I can't do.\n",5000);
Spoke("Chandler: If can invade Poland, there isn't anything I can't do.\n",5000);
Spoke("Joey: Listen, while you're on a roll, if you feel like you gotta make like a Western omelet or something... (Joey and Chandler taste the coffee, grimace, and pour it into a plant pot.) Although actually I'm really not that hungry...\n",5000);
Spoke("Monica: (entering, to herself) Oh good, Lenny and Squigy are here.\n",5000);
Spoke("All: Morning. Good morning.\n",5000);
Spoke("Paul: (entering from Monica's room) Morning.\n",5000);
Spoke("Joey: Morning, Paul.\n",5000);
Spoke("Rachel: Hello, Paul.\n",5000);
Spoke("Chandler: Hi, Paul, is it?\n",5000);
Spoke("Paul: Thank you!  Thank you so much!\n",5000);
Spoke("Monica: Stop!\n",5000);
Spoke("Paul: No, I'm telling you last night was like umm, all my birthdays, both graduations, plus the barn raising scene in Witness.\n",5000);
Spoke("Monica: We'll talk later.\n",5000);
Spoke("Paul: Yeah. (They kiss) Thank you. (Exits)\n",5000);
Spoke("Joey: That wasn't a real date?! What the hell do you do on a real date?\n",5000);
Spoke("Monica: Shut up, and put my table back.\n",5000);
Spoke("All: Okayyy! (They do so.)\n",5000);
Spoke("Chandler: All right, kids, I gotta get to work. If I don't input those numbers,... it doesn't make much of a difference... \n",5000);
Spoke("Rachel: So, like, you guys all have jobs?\n",5000);
Spoke("Monica: Yeah, we all have jobs. See, that's how we buy stuff.\n",5000);
Spoke("Joey: Yeah, I'm an actor.\n",5000);
Spoke("Rachel: Wow! Would I have seen you in anything?\n",5000);
Spoke("Joey: I doubt it. Mostly regional work.\n",5000);
Spoke("Monica: Oh wait, wait, unless you happened to catch the Reruns' production of Pinocchio, at the little theater in the park.\n",5000);
Spoke("Joey: Look, it was a job all right?\n",5000);
Spoke("Chandler: 'Look, Gippetto, I'm a real live boy.\n",5000);
Spoke("Joey: I will not take this abuse. (Walks to the door and opens it to leave.)\n",5000);
Spoke("Chandler: You're right, I'm sorry. \n",5000);
Spoke("Joey: You should both know, that he's a dead man.  Oh, Chandler? (Starts after Chandler.) Monica: So how you doing today? Did you sleep okay? Talk to Barry? I can't stop smiling.\n",5000);
Spoke("Rachel: I can see that. You look like you slept with a hanger in your mouth.\n",5000);
Spoke("Monica: I know, he's just so, so... Do you remember you and Tony DeMarco?\n",5000);
Spoke("Rachel: Oh, yeah.\n",5000);
Spoke("Monica: Well, it's like that. With feelings.\n",5000);
Spoke("Rachel: Oh wow. Are you in trouble.\n",5000);
Spoke("Monica: Big time!\n",5000);
Spoke("Rachel: Want a wedding dress?   Hardly used.\n",5000);
Spoke("Monica: I think we are getting a little ahead of selves here. Okay. Okay. I am just going to get up, go to work and not think about him all day. Or else I'm just gonna get up and go to work.\n",5000);
Spoke("Rachel: Oh, look, wish me luck!\n",5000);
Spoke("Monica: What for?\n",5000);
Spoke("Rachel: I'm gonna go get one of those (Thinks) job things.\n",5000);
Spoke("Frannie: Hey, Monica! \n",5000);
Spoke("Monica: Hey Frannie, welcome back! How was Florida? \n",5000);
Spoke("Frannie: You had sex, didn't you? \n",5000);
Spoke("Monica: How do you do that?\n",5000);
Spoke("Frannie: Oh, I hate you, I'm pushing my Aunt Roz through Parrot Jungle and you're having sex!  So? Who? \n",5000);
Spoke("Monica: You know Paul? \n",5000);
Spoke("Frannie: Paul the Wine Guy? Oh yeah, I know Paul. \n",5000);
Spoke("Monica: You mean you know Paul like I know Paul? \n",5000);
Spoke("Frannie: Are you kidding? I take credit for Paul. Y'know before me, there was no snap in his turtle for two years. \n",5000);
Spoke("Joey: (sitting on the arm of the couch)Of course it was a line! \n",5000);
Spoke("Monica: Why?! Why? Why, why would anybody do something like that? \n",5000);
Spoke("Ross: I assume we're looking for an answer more sophisticated than 'to get you into bed'. \n",5000);
Spoke("Monica: I hate men!  I hate men!\n",5000);
Spoke("Phoebe: Oh no, don't hate, you don't want to put that out into the universe.\n",5000);
Spoke("Monica: Is it me? Is it like I have some sort of beacon that only dogs and men with severe emotional problems can hear? \n",5000);
Spoke("Phoebe: All right, c'mere, gimme your feet. (She starts massaging them.) \n",5000);
Spoke("Monica: I just thought he was nice, y'know? \n",5000);
Spoke("Joey: (bursts out laughing again) I can't believe you didn't know it was a line! \n",5000);
Spoke("Rachel: Guess what? \n",5000);
Spoke("Ross: You got a job? \n",5000);
Spoke("Rachel: Are you kidding? I'm trained for nothing! I was laughed out of twelve interviews today.\n",5000); 
Spoke("Chandler: And yet you're surprisingly upbeat. \n",5000);
Spoke("Rachel: You would be too if you found John and David boots on sale, fifty percent off! \n",5000);
Spoke("Chandler: Oh, how well you know me...\n",5000); 
Spoke("Rachel: They're my new 'I don't need a job, I don't need my parents, I've got great boots' boots! \n",5000);
Spoke("Monica: How'd you pay for them? \n",5000);
Spoke("Rachel: Uh, credit card. \n",5000);
Spoke("Monica: And who pays for that? \n",5000);
Spoke("Rachel: Um... my... father. \n",5000);
Spoke("Rachel: Oh God, come on you guys, is this really necessary?  I mean, I can stop charging anytime I want. \n",5000);
Spoke("Monica: C'mon, you can't live off your parents your whole life. \n",5000);
Spoke("Rachel: I know that. That's why I was getting married. \n",5000);
Spoke("Phoebe: Give her a break, it's hard being on your own for the first time.\n",5000); 
Spoke("Rachel: Thank you. \n",5000);
Spoke("Phoebe: You're welcome. I remember when I first came to this city. I was fourteen. My mom had just killed herself and my step-dad was back in prison, and I got here, and I didn't know anybody. And I ended up living with this albino guy who was, like, cleaning windshields outside port authority, and then he killed himself, and then I found aromatherapy. So believe me, I know exactly how you feel. \n",5000);
Spoke("Ross: The word you're looking for is 'Anyway'... \n",5000);
Spoke("Monica: All right, you ready?\n",5000);
Spoke("Rachel: No.  No, no, I'm not ready!  How can I be ready?  Come on, I can't do this!\n",5000);
Spoke("Monica: You can, I know you can! \n",5000);
Spoke("Rachel: I don't think so.\n",5000);
Spoke("Ross: Come on, you made coffee!   You can do anything! (Chandler slowly tries to hide the now dead plant from that morning when he and Joey poured their coffee into it.)\n",5000);
Spoke("Ross: C'mon, cut. Cut, cut, cut,... \n",5000);
Spoke("All: Cut, cut, cut, cut, cut, cut, cut... (She cuts one of them and they cheer.)\n",5000);
Spoke("Rachel: Y'know what?  I think we can just leave it at that.  It's kinda like a symbolic gesture...\n",5000);
Spoke("Monica:  Rachel!  That was a library card! \n",5000);
Spoke("All: Cut, cut, cut, cut, cut, cut, cut..\n",5000);
Spoke("Chandler: (as Rachel is cutting up her cards) Y'know, if you listen closely, you can hear a thousand retailers scream. \n",5000);
Spoke("Monica: Welcome to the real world! It sucks. You're gonna love it!  \n",5000);
Spoke("Monica: Well, that's it (To Ross) You gonna crash on the couch? \n",5000);
Spoke("Ross: No. No, I gotta go home sometime. \n",5000);
Spoke("Monica: You be okay? \n",5000);
Spoke("Ross: Yeah.\n",5000); 
Spoke("Rachel: Hey Mon, look what I just found on the floor. (Monica smiles.) What? \n",5000);
Spoke("Monica: That's Paul's watch. You just put it back where you found it. Oh boy. Alright. Goodnight, everybody. \n",5000);
Spoke("Ross and Rachel: Goodnight.\n",5000);
Spoke("Ross: Mmm. (They both reach for the last cookie) Oh, no- \n",5000);
Spoke("Rachel: Sorry- \n",5000);
Spoke("Ross: No no no, go- \n",5000);
Spoke("Rachel: No, you have it, really, I don't want it- \n",5000);
Spoke("Ross: Split it? \n",5000);
Spoke("Rachel: Okay. \n",5000);
Spoke("Ross: Okay. (They split it.) You know you probably didn't know this, but back in high school, I had a, um, major crush on you. \n",5000);
Spoke("Rachel: I knew. \n",5000);
Spoke("Ross: You did! Oh.... I always figured you just thought I was Monica's geeky older brother. \n",5000);
Spoke("Rachel: I did. \n",5000);
Spoke("Ross: Oh. Listen, do you think- and try not to let my intense vulnerability become any kind of a factor here- but do you think it would be okay if I asked you out? Sometime? Maybe?\n",5000); 
Spoke("Rachel: Yeah, maybe... \n",5000);
Spoke("Ross: Okay... okay, maybe I will... \n",5000);
Spoke("Rachel: Goodnight. \n",5000);
Spoke("Ross: Goodnight.  \n",5000);
Spoke("Monica: See ya.... Waitwait, what's with you? \n",5000);
Spoke("Ross: I just grabbed a spoon. (Ross exits and Monica has no idea what that means.) \n",5000);
Spoke("Joey: I can't believe what I'm hearing here. \n",5000);
Spoke("Phoebe: (sings) I can't believe what I'm hearing here... \n",5000);
Spoke("Monica: What? I-I said you had a- \n",5000);
Spoke("Phoebe: (sings) What I said you had... \n",5000);
Spoke("Monica: (to Phoebe) Would you stop? \n",5000);
Spoke("Phoebe: Oh, was I doing it again?\n",5000);
Spoke("All: Yes!\n",5000);
Spoke("Monica: I said that you had a nice butt, it's just not a great butt.\n",5000);
Spoke("Joey: Oh, you wouldn't know a great butt if it came up and bit ya.\n",5000);
Spoke("Ross: There's an image. \n",5000);
Spoke("Rachel: (walks up with a pot of coffee) Would anybody like more coffee? \n",5000);
Spoke("Chandler: Did you make it, or are you just serving it? \n",5000);
Spoke("Rachel: I'm just serving it. \n",5000);
Spoke("All: Yeah. Yeah, I'll have a cup of coffee.\n",5000); 
Spoke("Chandler: Kids, new dream... I'm in Las Vegas. (Rachel sits down to hear Chandler's dream.)\n",5000);
Spoke("Customer: (To Rachel) Ahh, miss?   More coffee? \n",5000);
Spoke("Rachel: Ugh. (To another customer that's leaving.) Excuse me, could you give this to that guy over there? (Hands him the coffee pot.) Go ahead. (He does so.) Thank you. (To the gang.) Sorry.  Okay, Las Vegas.\n",5000);
Spoke("Chandler: Okay, so, I'm in Las Vegas... I'm Liza Minelli- \n",5000);

 } 
void Spoke(char name[1000],int time)
{
	Sleep(time);
	printf("%s",name);
}
